name: Check installation steps

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run setup.sh
        run: |
          ./setup.sh